---
- name: Gather version information from Cisco router via SSH
  hosts: "{{ target_hosts | default('all') }}"
  connection: network_cli
  gather_facts: no
  vars:
    ansible python module location: /usr/lib/python3.10/site-packages/ansible
    ansible collection location: /opt/ansible/network/collections
    ansible_network_os: ios
  tasks:
    - name: show version
      cisco.ios.ios_command:
        commands:
          - show version

    - name: Display version information
      debug:
        var: version_info.stdout_lines
