---
- name: Gather version information from Cisco router via SSH
  ansible.builtin.pip:
    name: ansible-pylibssh
  hosts: "{{ target_hosts | default('all') }}"
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: cisco.ios.ios
  tasks:
    - name: Get version information
      ios_command:
        commands:
          - show version
      register: version_info

    - name: Display version information
      debug:
        var: version_info.stdout_lines
