---
- name: Gather version information from Cisco router via SSH
  hosts: "{{ target_hosts | default('all') }}"
  connection: network_cli
  gather_facts: no
  vars:
    ansible_python_interpreter: /ansible/ansible-venv/bin/python
    ansible_network_os: ios
  tasks:
    - name: show version
      cisco.ios.ios_command:
        commands:
          - show version

    - name: Display version information
      debug:
        var: version_info.stdout_lines
