---
- name: Gather version information from Cisco router via SSH
  hosts: cisco_router
  connection: paramiko
  gather_facts: no
  tasks:
    - name: Get version information
      ios_command:
        commands:
          - show version
      register: version_info

    - name: Display version information
      debug:
        var: version_info.stdout_lines
